name: base
channels:
  - defaults
  - anaconda
  - menpo
  - conda-forge
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0=py36_0
  - alabaster=0.7.12=py36_0
  - anaconda-client=1.7.2=py36_0
  - anaconda-navigator=1.9.12=py36_0
  - argon2-cffi=20.1.0=py36he774522_1
  - asteval=0.9.16=pyh5ca1d4c_0
  - async_generator=1.10=py36h28b3542_0
  - atomicwrites=1.4.0=py_0
  - attrs=20.3.0=pyhd3eb1b0_0
  - babel=2.9.0=pyhd3eb1b0_0
  - backcall=0.2.0=py_0
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - blosc=1.20.1=h7bd577a_0
  - brotlipy=0.7.0=py36h2bbff1b_1003
  - bzip2=1.0.6=vc14hdec8e7a_1
  - ca-certificates=2020.12.8=haa95532_0
  - certifi=2020.12.5=py36haa95532_0
  - cffi=1.14.4=py36hcd4344a_0
  - chardet=4.0.0=py36haa95532_1003
  - cloudpickle=1.6.0=py_0
  - clyent=1.2.2=py36_1
  - cmarkgfm=0.4.2=py36he774522_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda=4.9.2=py36haa95532_0
  - conda-build=3.15.1=py36_0
  - conda-package-handling=1.7.2=py36h76e460a_0
  - console_shortcut=0.1.1=3
  - cryptography=3.1.1=py36h7a1dbc1_0
  - cycler=0.10.0=py36haa95532_0
  - cython=0.29.21=py36ha925a31_0
  - cytoolz=0.11.0=py36he774522_0
  - dask-core=2020.12.0=pyhd3eb1b0_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - docutils=0.16=py36_1
  - entrypoints=0.3=py36_0
  - ffmpeg=4.2.2=he774522_0
  - filelock=3.0.12=py_0
  - freetype=2.8=vc14h17c9bdf_0
  - future=0.18.2=py36_1
  - glob2=0.7=py_0
  - hdf5=1.8.18=vc14h7a021fe_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=vc14hc45fdbb_0
  - idna=2.10=py_0
  - imageio=2.9.0=py_0
  - imageio-ffmpeg=0.4.3=pyhd8ed1ab_0
  - imagesize=1.2.0=py_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - iniconfig=1.1.1=py_0
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py36h5ca1d4c_0
  - ipython=7.16.1=py36h5ca1d4c_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.1=pyhd3eb1b0_0
  - jedi=0.18.0=py36haa95532_0
  - jinja2=2.11.2=py_0
  - joblib=1.0.0=pyhd3eb1b0_0
  - jpeg=9b=vc14h4d7706e_1
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.7.0=py36haa95532_0
  - jupyterlab=2.2.6=py_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=1.2.0=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.0=py36hd77b12b_0
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - lmfit=1.0.0=py_0
  - lz4-c=1.9.2=hf4a77e7_3
  - lzo=2.10=vc14h0a64fa6_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py36he774522_0
  - matplotlib=2.2.2=py36h153e9ff_1
  - menuinst=1.4.16=py36he774522_1
  - mistune=0.8.4=py36he774522_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36h196d8e1_0
  - mkl_fft=1.2.0=py36h45dec08_0
  - mkl_random=1.1.1=py36h47e9c7a_0
  - more-itertools=8.6.0=pyhd3eb1b0_0
  - moviepy=1.0.1=py_0
  - msys2-conda-epoch=20160418=1
  - navigator-updater=0.2.1=py36_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py36_0
  - nbformat=5.0.8=py_0
  - nest-asyncio=1.4.3=pyhd3eb1b0_0
  - networkx=2.5=py_0
  - notebook=6.1.6=py36haa95532_0
  - numexpr=2.7.2=py36hcbcaa1e_0
  - numpy=1.19.1=py36h5510c5b_0
  - numpy-base=1.19.1=py36ha3acd2a_0
  - olefile=0.46=py36_0
  - openssl=1.1.1i=h2bbff1b_0
  - packaging=20.8=pyhd3eb1b0_0
  - pandoc=2.11=h9490d1a_0
  - pandocfilters=1.4.3=py36haa95532_1
  - parso=0.7.0=py_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=5.0.0=py36_0
  - pkginfo=1.6.1=py36haa95532_0
  - pluggy=0.13.1=py36_0
  - powershell_shortcut=0.0.1=2
  - proglog=0.1.9=py_0
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - psutil=5.7.2=py36he774522_0
  - py=1.10.0=pyhd3eb1b0_0
  - pycosat=0.6.3=py36h2bbff1b_0
  - pycparser=2.20=py_2
  - pygments=2.7.3=pyhd3eb1b0_0
  - pyopengl=3.1.1a1=py36_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py36h6538335_2
  - pyrsistent=0.17.3=py36he774522_0
  - pysocks=1.7.1=py36haa95532_0
  - pytables=3.4.4=py36h0f9c03a_0
  - pytest=6.2.1=py36haa95532_0
  - python=3.6.12=h5500b2f_2
  - python-dateutil=2.8.1=py_0
  - pytz=2020.5=pyhd3eb1b0_0
  - pywavelets=1.1.1=py36he774522_2
  - pywin32=227=py36he774522_1
  - pywinpty=0.5.7=py36_0
  - pyyaml=5.3.1=py36he774522_0
  - pyzmq=20.0.0=py36hd77b12b_1
  - qt=5.9.7=vc14h73c81de_0
  - qtpy=1.9.0=py_0
  - readme_renderer=24.0=py36_0
  - requests=2.25.1=pyhd3eb1b0_0
  - requests-toolbelt=0.9.1=py_0
  - ruamel_yaml=0.15.87=py36he774522_0
  - scikit-image=0.16.2=py36h47e9c7a_0
  - scikit-learn=0.23.2=py36h47e9c7a_0
  - scipy=1.2.1=py36h29ff71c_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=51.0.0=py36haa95532_2
  - sip=4.19.8=py36h6538335_0
  - six=1.15.0=py36haa95532_0
  - snowballstemmer=2.0.0=py_0
  - soupsieve=2.1=pyhd3eb1b0_0
  - sphinx=3.4.2=pyhd3eb1b0_0
  - sphinxcontrib-applehelp=1.0.2=py_0
  - sphinxcontrib-devhelp=1.0.2=py_0
  - sphinxcontrib-htmlhelp=1.0.3=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.3=py_0
  - sphinxcontrib-serializinghtml=1.1.4=py_0
  - sqlite=3.33.0=h2a8f88b_0
  - terminado=0.9.2=py36haa95532_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - toml=0.10.1=py_0
  - toolz=0.11.1=py_0
  - tornado=6.1=py36h2bbff1b_0
  - tqdm=4.55.1=pyhd3eb1b0_0
  - traitlets=4.3.3=py36_0
  - twine=1.13.0=py_1
  - uncertainties=3.1.5=pyhd8ed1ab_0
  - urllib3=1.26.2=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py36_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py36_0
  - win_inet_pton=1.1.0=py36haa95532_0
  - wincertstore=0.2=py36h7fe50ca_0
  - winpty=0.4.3=4
  - xmltodict=0.12.0=py_0
  - xz=5.2.5=h62dcd97_0
  - yaml=0.1.7=vc14h4cb57cf_1
  - zeromq=4.3.3=ha925a31_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=vc14h1cdd9ab_1
  - zstd=1.4.5=h04227a9_0
  - pip:
    - apptools==4.4.0
    - configobj==5.0.6
    - envisage==4.8.0
    - fabio==0.9.0
    - h5py==2.10.0
    - hdf5plugin==1.4.1
    - libtiff==0.4.2
    - mayavi==4.7.1
    - pip==19.1.1
    - pyface==6.1.2
    - silx==0.13.1
    - traits==5.1.2
    - traitsui==6.1.3
    - vtk==8.1.2
    - xrayutilities==1.6.0
prefix: C:\Users\carnisj\AppData\Local\Continuum\anaconda3
