name: bcdi
channels:
  - defaults
  - anaconda
  - menpo
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - hdf5plugin
  - h5py
  - traits
  - pyqt
  - pyqtgraph
  - mayavi
  - vtk
  - importlib_resources
  - xrayutilities
  - fabio
  - silx
  - pytables
  - lmfit
  - moviepy
  - pillow
  - black
  - doit
  - coverage